# Generated by Django 4.2.2 on 2023-06-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_publication_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='address',
            new_name='title',
        ),
    ]
