# Generated by Django 4.2.2 on 2023-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_address_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
